#!/bin/bash

#PBS -N DucFileDel
#PBS -l nodes=1:ppn=16
#PBS -l walltime=60:00:00
#PBS -l mem=32g
#PBS -e /hpc/puhome/21040136r/my_programs/DUC_Programs/duc_error_file
#PBS -o /hpc/puhome/21040136r/my_programs/DUC_Programs/duc_outfile
# Job queue name: ho0gen1
# name of nodes: h05gen1, h05gen2, h05dev
#PBS -q h05gen1

EXEC=python
cd /hpc/puhome/21040136r/my_programs/DUC_Programs/MIP_test_code
module load Anaconda3-2022.05
source activate my_env


$EXEC duc_data_file_clearing.py